/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author JorgeIgnacio
 */
public class JFrame_VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_VentanaPrincipal
     */
    public JFrame_VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar_VentanaPrincipal = new javax.swing.JMenuBar();
        jMenu_Archivo = new javax.swing.JMenu();
        jMenuItem_Salir = new javax.swing.JMenuItem();
        jMenu_Registro = new javax.swing.JMenu();
        jMenuItem_RegistroEstudiate = new javax.swing.JMenuItem();
        jMenuItem_RegistroCurso = new javax.swing.JMenuItem();
        jMenu_Matricula = new javax.swing.JMenu();
        jMenuItem_MatriculaEstudiante = new javax.swing.JMenuItem();
        jMenu_Reporte = new javax.swing.JMenu();
        jMenuItem_ReporteCurso = new javax.swing.JMenuItem();
        jMenuItem_Estudiante = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu_Archivo.setText("Archivo");

        jMenuItem_Salir.setText("Salir");
        jMenu_Archivo.add(jMenuItem_Salir);

        jMenuBar_VentanaPrincipal.add(jMenu_Archivo);

        jMenu_Registro.setText("Registro");

        jMenuItem_RegistroEstudiate.setText("Registro de Estudiantes");
        jMenu_Registro.add(jMenuItem_RegistroEstudiate);

        jMenuItem_RegistroCurso.setText("Registro de Cursos");
        jMenu_Registro.add(jMenuItem_RegistroCurso);

        jMenuBar_VentanaPrincipal.add(jMenu_Registro);

        jMenu_Matricula.setText("Matrícula");

        jMenuItem_MatriculaEstudiante.setText("Matrícula de Estudiantes");
        jMenu_Matricula.add(jMenuItem_MatriculaEstudiante);

        jMenuBar_VentanaPrincipal.add(jMenu_Matricula);

        jMenu_Reporte.setText("Reporte");

        jMenuItem_ReporteCurso.setText("Reporte de Cursos");
        jMenu_Reporte.add(jMenuItem_ReporteCurso);

        jMenuItem_Estudiante.setText("Reporte de Estudiantes");
        jMenu_Reporte.add(jMenuItem_Estudiante);

        jMenuBar_VentanaPrincipal.add(jMenu_Reporte);

        setJMenuBar(jMenuBar_VentanaPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar_VentanaPrincipal;
    private javax.swing.JMenuItem jMenuItem_Estudiante;
    private javax.swing.JMenuItem jMenuItem_MatriculaEstudiante;
    private javax.swing.JMenuItem jMenuItem_RegistroCurso;
    private javax.swing.JMenuItem jMenuItem_RegistroEstudiate;
    private javax.swing.JMenuItem jMenuItem_ReporteCurso;
    private javax.swing.JMenuItem jMenuItem_Salir;
    private javax.swing.JMenu jMenu_Archivo;
    private javax.swing.JMenu jMenu_Matricula;
    private javax.swing.JMenu jMenu_Registro;
    private javax.swing.JMenu jMenu_Reporte;
    // End of variables declaration//GEN-END:variables
}
