/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador_JFrame_Estudiante;
/**
 *
 * @author JorgeIgnacio
 */
public class JPanel_Botones extends javax.swing.JPanel {

    Controlador_JFrame_Estudiante controlador;
    /**
     * Creates new form JP_Botones
     */
    public JPanel_Botones() {
        initComponents();
    }

    public void agregarEventosEstudiante(Controlador_JFrame_Estudiante controlador){
        
        this.controlador=controlador;
        
        this.jB_RegistroEst.addActionListener(controlador);
        this.jB_ModificarEst.addActionListener(controlador);
        this.jB_EliminarEst.addActionListener(controlador);
        this.jB_ConsultarEst.addActionListener(controlador);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jB_RegistroEst = new javax.swing.JButton();
        jB_ModificarEst = new javax.swing.JButton();
        jB_EliminarEst = new javax.swing.JButton();
        jB_ConsultarEst = new javax.swing.JButton();

        jB_RegistroEst.setText("Registro");

        jB_ModificarEst.setText("Modificar");

        jB_EliminarEst.setText("Eliminar");

        jB_ConsultarEst.setText("Consultar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jB_EliminarEst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jB_ModificarEst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jB_RegistroEst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jB_ConsultarEst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jB_RegistroEst)
                .addGap(18, 18, 18)
                .addComponent(jB_ModificarEst)
                .addGap(18, 18, 18)
                .addComponent(jB_EliminarEst)
                .addGap(18, 18, 18)
                .addComponent(jB_ConsultarEst))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_ConsultarEst;
    private javax.swing.JButton jB_EliminarEst;
    private javax.swing.JButton jB_ModificarEst;
    private javax.swing.JButton jB_RegistroEst;
    // End of variables declaration//GEN-END:variables
}
