/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author JorgeIgnacio
 */
public class JPanel_InformacionCurso extends javax.swing.JPanel {

    /**
     * Creates new form JPanel_InformacionCurso
     */
    public JPanel_InformacionCurso() {
        initComponents();
    }
    
    /*
    Método que almacena la informacion obtenida
    de un curso en un arreglo
    */
    public String[] obtenerInformacionCurso(){
        
        String informacion[];
        informacion = new String[3];
        
        informacion[0] = this.jTextField_NombreCurso.getText();
        informacion[1] = this.jTextField_SiglaCurso.getText();
        informacion[2] = this.jTextField_CreditoCurso.getText();
        
        return informacion;
        
    }//Fin_obtenerInformacionCurso
    
    /*
    Método que obtiene la sigla del curso del jTextField
    */
    public String obtenerSiglaCurso(){
        return this.jTextField_SiglaCurso.getText();
    }//Fin obtenerSiglaCurso
    
    /*
    Método que obtiene el nombre del curso del jTextField
    */
    public String obtenerNombreCurso(){
        return this.jTextField_NombreCurso.getText();
    }//Fin obtenerNombreCurso
    
    /*
    Método que obtiene la cantidad de créditos del curso del jTextField
    */
    public String obtenerCreditoCurso(){
        return this.jTextField_CreditoCurso.getText();
    }//Fin obtenerCreditoCurso

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_NombreCurso = new javax.swing.JLabel();
        jTextField_NombreCurso = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField_SiglaCurso = new javax.swing.JTextField();
        jLabel_CreditoCurso = new javax.swing.JLabel();
        jTextField_CreditoCurso = new javax.swing.JTextField();

        jLabel_NombreCurso.setText("Nombre del curso");

        jLabel1.setText("Sigla del curso");

        jLabel_CreditoCurso.setText("Créditos del curso");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_CreditoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_NombreCurso)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_SiglaCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField_NombreCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addComponent(jTextField_CreditoCurso)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_SiglaCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_NombreCurso)
                    .addComponent(jTextField_NombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_CreditoCurso)
                    .addComponent(jTextField_CreditoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_CreditoCurso;
    private javax.swing.JLabel jLabel_NombreCurso;
    private javax.swing.JTextField jTextField_CreditoCurso;
    private javax.swing.JTextField jTextField_NombreCurso;
    private javax.swing.JTextField jTextField_SiglaCurso;
    // End of variables declaration//GEN-END:variables
}
