/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador_JFrame_MatriculaProceso;

/**
 *
 * @author JorgeIgnacio
 */
public class JPanel_BotonMatricula extends javax.swing.JPanel {

    Controlador_JFrame_MatriculaProceso controladorMatricula;
    /**
     * Creates new form JPanel_Matricular
     */
    public JPanel_BotonMatricula() {
        initComponents();
    }
    
    public void agregarEventosMatricula(Controlador_JFrame_MatriculaProceso controladorMatricula){
        this.jButton_Matricular.addActionListener(controladorMatricula);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Matricular = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(90, 45));

        jButton_Matricular.setText("Matricular");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_Matricular)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_Matricular)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Matricular;
    // End of variables declaration//GEN-END:variables
}
